.github/workflows/dev-deploy.yml, .github/workflows/prod-deploy.yml, .github/workflows/stage-deploy.yml, scripts/dev-deploy.sh, scripts/prod-deploy.sh, scripts/stage-deploy.sh
Added a new GitHub Actions workflow for the development environment.
Added a staging workflow that mirrors the production environment but allows for final testing before production deployment.
Added production workflow to automate deployment to the live environment.
Created scripts folder to facilitate the three workflows, including dotnet environment setup, dependency installation, and publishing.
=> added dev, prod, and stage workflow and script

scripts/dev-deploy.sh
--no-restore during build and --no-build during publish.
=> ci(deploy): no restore during build and publish

src/Hng.Application/ConfigureApplication.cs, src/Hng.Application/Hng.Application.csproj, src/Hng.Domain/Entities/User.cs, src/Hng.Infrastructure/ConfigureInfrastructure.cs, src/Hng.Infrastructure/Hng.Infrastructure.csproj, src/Hng.Infrastructure/Migrations/20240723142321_AddPasswordToUserEntity.Designer.cs, src/Hng.Infrastructure/Migrations/20240723142321_AddPasswordToUserEntity.cs, src/Hng.Infrastructure/Services/Interfaces/IPasswordService.cs, src/Hng.Infrastructure/Services/Interfaces/ITokenService.cs, src/Hng.Infrastructure/Services/PasswordService.cs, src/Hng.Infrastructure/Services/TokenService.cs, src/Hng.Web/Program.cs, src/Hng.Web/appsettings.json
Set up Infrastructure required for Authentication and Authorization for The Boiler Plate. It Should support JWT Authentication, Password Hashing and Password Comparing, these would be used for the Signup and Register Endpoints
Partially Implements issue #8 and issue #67
Generate JWT Contatining User Details, support Password Hashing And Comparison, Register Authentication Middlewares 
Generate JWT Contatining User Details, support Password Hashing And Comparison, Register Authentication Middlewares 
* Created Password Service and Interface
* Implemented Token Services and Interface
* Registered Authentication Services in ApplicationConfigurations 
* Ensured Swagger Docs support
* Added Authentication Middleware
🚨Please review the [contribution guideline](CONTRIBUTING.md) for this …
=> Feat(Authentication): Implement Base Infrastructure Required for Authentication 

src/Hng.Web/Program.cs
Moved the API documentation to a different route.
Configure the route of Swagger UI using Swashbuckle.
- Modified the Startup.cs file to configure custom routes for Swagger JSON and Swagger UI.
- Set Swagger JSON endpoint to /docs/{documentName}/swagger.json.
- Updated SwaggerEndpoint to match the new JSON location.
=> feat: Moved Swagger UI to /docs

src/Hng.Application.Test/Features/UserManagement/LoginUserCommandShould.cs, src/Hng.Application/Features/UserManagement/Commands/CreateUserLoginCommand.cs, src/Hng.Application/Features/UserManagement/Dtos/UserLoginRequestDto.cs, src/Hng.Application/Features/UserManagement/Dtos/UserLoginResponseDto.cs, src/Hng.Application/Features/UserManagement/Handlers/LoginUserCommandHandler.cs, src/Hng.Application/Hng.Application.csproj, src/Hng.Web/Controllers/AuthenticationController.cs
Implement a robust login feature to streamline user access and authentication processes. This feature should encompass secure user logins, password protection, and account security measures.
Github Issue : [ #10](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/10#issue-2411494456) 
-  The endpoint must return a 422 error for missing or invalid input with an appropriate error message.
-  A 401 status code should be returned for invalid credentials with an appropriate error message.
-  A successful login should return a 200 response with success message
-  User's credentials transmitted securely to the Backend
-  Once validation checks are passed, JWT token is generated for the user encoded using the user mail, user id, and first and last names and returned as part of the …
=> feat: authentication - user login

src/Hng.Application/Features/UserManagement/Dtos/UserResponseDto.cs
Changed UserResponseDto to snake-case
=> fix(authentication) user-sign-up

.githooks/commit-msg
Enhances the `.githooks/commit-msg` script to enforce the Conventional Commit standard for commit messages.
Refactor the commit message validation script to ensure compliance with the Conventional Commit convention, improving message consistency and clarity.
- Improved the regular expression for more accurate validation of commit messages.
- Added checks to verify proper formatting, including type and optional scope.
- Enhanced error messages and provided guidance for incorrect commit messages.
🚨 Please review the [contribution guideline](CONTRIBUTING.md) for this repository.
=> Enhance Commit Message Validation for Conventional Commits

src/Hng.Domain/Entities/Organization.cs, src/Hng.Domain/Entities/Subscription.cs, src/Hng.Domain/Entities/Transaction.cs, src/Hng.Domain/Entities/User.cs, src/Hng.Domain/EntitiesConfigurations/SubscriptionConfiguration.cs, src/Hng.Domain/Enums/SubscriptionFrequency.cs, src/Hng.Domain/Enums/SubscriptionPlan.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/20240728133306_Added Subscription Table.Designer.cs, src/Hng.Infrastructure/Migrations/20240728133306_Added Subscription Table.cs, src/Hng.Web/Program.cs
**Closes #150 **
To create the subscription table.
Created subscription Table for the Team working on Subscription.
=> feat: Subscription DB Schema

src/Hng.Application.Test/Features/Job/CreateJobCommandShould.cs, src/Hng.Application.Test/Features/Job/CreateJobShould.cs, src/Hng.Application/Features/Jobs/Commands/CreateJobCommand.cs, src/Hng.Application/Features/Jobs/Dtos/CreateJobDto.cs, src/Hng.Application/Features/Jobs/Dtos/JobDto.cs, src/Hng.Application/Features/Jobs/Handlers/CreateJobCommandHandler.cs, src/Hng.Application/Features/Jobs/Mappers/JobMapperProfile.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Services/PaystackClient.cs, src/Hng.Application/Hng.Application.csproj, src/Hng.Application/Utils/LowerCaseNamingPolicy.cs, src/Hng.Domain/Entities/Job.cs, src/Hng.Domain/Enums/ExperienceLevel.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs, src/Hng.Web/Controllers/JobController.cs
This pull request addresses issue #138, which involved implementing and testing the job creation functionality.
- Implement `CreateJobCommandHandler` to handle the creation of job entities.
- Dependencies for the job repository and mapper are injected through the constructor and assigned to read-only fields.
- The `Handle` method maps the incoming `CreateJobDto` to a `Job` entity, sets the `DatePosted` property, and adds the job to the repository.
- The created job entity is then mapped to a `JobDto` and returned.
- Update the `JobsController` to handle job creation requests.
- The `CreateJob` action method in the controller uses MediatR to send the `CreateJobCommand` and handle the response.
- The action method returns a `CreatedAtAction` result with the details of the created job.
- …
=> feat: job - create job

src/Hng.Application.Test/Features/Products/CreateProductTest.cs, src/Hng.Application/Features/Products/Commands/CreateProductCommand.cs, src/Hng.Application/Features/Products/Dtos/ProductCreationDto.cs, src/Hng.Application/Features/Products/Dtos/ProductDto.cs, src/Hng.Application/Features/Products/Handlers/CreateProductHandler.cs, src/Hng.Application/Features/Products/Mappers/ProductMapperProfile.cs, src/Hng.Web/Controllers/ProductController.cs
Create an api endpoint to create new product
Link to issue #84 
To create an api endpoint that can allow new product to be created
1. Created an endpoint
2. Added necessary model and dtos
3. tested the endpoint 
=> feat: added create product endpoint

src/Hng.Application.Test/Features/Job/GetJobByIdQueryShould.cs, src/Hng.Application/Features/Jobs/Handlers/GetJobByIdRequestHandler.cs, src/Hng.Application/Features/Jobs/Queries/GetJobByIdQuery.cs, src/Hng.Application/Hng.Application.csproj, src/Hng.Web/Controllers/JobController.cs
The issue was about implementing the functionality to retrieve a job listing by its ID.
**Closes #156**
=> feat: jobs - get job by id

src/Hng.Application.Test/Features/PaymentIntegrations/Paystack/SubscriptionTransactionSuccessfulShould.cs, src/Hng.Application/ConfigureApplication.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Dtos/Requests/InitializeTransactionRequest.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Dtos/Requests/InitiateSubscriptionTransactionCommand.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Dtos/Requests/TransactionsWebhookCommand.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Dtos/Responses/InitiateSubscriptionTransactionResponse.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Handlers/Commands/InitializeTransactionCommandHandler.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Handlers/Commands/InitiateSubscriptionTransactionHandler.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Handlers/Commands/SubscriptionsTransactionCommandHandler.cs, src/Hng.Application/Utils/GenerateTransactionReference.cs, src/Hng.Domain/Enums/SubscriptionFrequency.cs, src/Hng.Web/Controllers/TransactionsController.cs
**Closes #104 **
To provide an endpoint for initiate checkout flow for Paid Subscriptions Plan
Implemented the endpoint for Paid Subscription Plan and the Handler for webhook
=> [Feat] Implement Complete Transaction Flow Initiate, Webhook Transactions for Paid Subscription Plan

src/Hng.Application.Test/Features/Subscriptions/CreateFreeSubscriptionPlanShould.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Dtos/Requests/InitiateSubscriptionTransactionCommand.cs, src/Hng.Application/Features/PaymentIntegrations/Paystack/Handlers/Commands/SubscriptionsTransactionCommandHandler.cs, src/Hng.Application/Features/Subscriptions/Dtos/Requests/SubscribeFreePlan.cs, src/Hng.Application/Features/Subscriptions/Dtos/Responses/SubscribeFreePlanResponse.cs, src/Hng.Application/Features/Subscriptions/Handlers/Commands/CreateFreeSubscriptionPlanHandler.cs, src/Hng.Web/Controllers/SubscriptionsController.cs, src/Hng.Web/Controllers/TransactionsController.cs
**Closes #150 **
To create an endpoint for free subscription
Provided the end point to sub to free subscription
=> [Feat] Implement Create Subscription Endpoint with Free Plan 

src/Hng.Application.Test/Features/Job/GetJobsQueryShould.cs, src/Hng.Application/Features/Jobs/Handlers/GetJobsQueryHandler.cs, src/Hng.Application/Features/Jobs/Queries/GetJobsQuery.cs, src/Hng.Web/Controllers/JobController.cs
This pull request implements the feature to get all job listings.
**Closes #162 **
- Implemented `GetJobsQuery` to request all job listings
- Created `GetJobsQueryHandler` to process the query and retrieve job data
- Developed `JobDto` to represent job data in the application layer
- Set up `JobMapperProfile` for mapping between `Job` entities and `JobDto`
- Implemented unit tests in `GetJobsQueryShould` to ensure correct functionality
- Added necessary repository methods to fetch job data
- Ensured proper mapping of all job properties, including experience level
- Unit tests have been implemented and are passing
- Manual testing has been performed to ensure the feature works as expected
=> feat: jobs - get all job listings

src/Hng.Application/ConfigureApplication.cs, src/Hng.Web/Program.cs
=> feat: add cors policy,

src/Hng.Application/Features/UserManagement/Dtos/GoogleLoginRequestDto.cs, src/Hng.Web/Controllers/AuthenticationController.cs
This pull requests makes the changes to the google auth rout as specified in the unified route document
- Change route to google from google_login
- Edit request body for google auth to snake case
=> fix(Auth): Change google auth route

src/Hng.Infrastructure/Migrations/20240729200828_messages.cs
This Pr fixes the repeated create jobs migration
=> Fix(db):fix repeated jobs migration

src/Hng.Application/Features/EmailTemplates/DTOs/EmailTemplateResponseDTO.cs, src/Hng.Application/Features/EmailTemplates/Handlers/GetAllEmailTemplatesQueryHandler.cs, src/Hng.Application/Features/EmailTemplates/Mappers/EmailTemplateMapperProfile.cs, src/Hng.Application/Features/EmailTemplates/Queries/GetAllEmailTemplatesQuery.cs, src/Hng.Domain/Entities/EmailTemplate.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/20240730204403_EmailTemplates.Designer.cs, src/Hng.Infrastructure/Migrations/20240730204403_EmailTemplates.cs, src/Hng.Web/Controllers/EmailTemplateController.cs
Implemented endpoint to get all email templates.
Allow for viewing all email templates
- Created data models and migrations for email templates
- Created controller, query, and handler for getting all the email templates.
=> feat: created endpoints to get email templates

src/Hng.Application.Test/Features/Notifications/CreateNotificationHandlerShould.cs, src/Hng.Application/Features/Notifications/Commands/CreateNotificationCommand.cs, src/Hng.Application/Features/Notifications/Dtos/CreateNotificationDto.cs, src/Hng.Application/Features/Notifications/Dtos/NotificationDto.cs, src/Hng.Application/Features/Notifications/Handlers/CreateNotificationHandler.cs, src/Hng.Application/Features/Notifications/Mappers/NotificationMapperProfile.cs, src/Hng.Domain/Entities/Notification.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/20240730222425_add notification.Designer.cs, src/Hng.Infrastructure/Migrations/20240730222425_add notification.cs, src/Hng.Web/Controllers/NotificationController.cs
**Closes #141**
Develop and implement the backend components necessary to manage user notification preferences. This includes creating the data models, database schema, API endpoints, and ensuring integration with existing services.
Design and create a database schema for storing notification preferences.
Develop API endpoints for managing notification settings.
Integrate the notification settings feature with existing user services.
Add authentication to ensure only authenticated users can access the endpoints.
=> feat(notification): Implement Post Endpoint for Notification Settings

src/Hng.Application.Test/Features/Notifications/CreateNotificationHandlerShould.cs, src/Hng.Application/Features/Notifications/Commands/CreateNotificationCommand.cs, src/Hng.Application/Features/Notifications/Dtos/CreateNotificationDto.cs, src/Hng.Application/Features/Notifications/Handlers/CreateNotificationHandler.cs, src/Hng.Web/Controllers/NotificationController.cs
**Closes #141**
Develop and implement the backend components necessary to manage user notification preferences. This includes creating the data models, database schema, API endpoints, and ensuring integration with existing services.
Design and create a database schema for storing notification preferences.
Develop API endpoints for managing notification settings.
Integrate the notification settings feature with existing user services.
Add authentication to ensure only authenticated users can access the endpoints.
=> [FEAT] Implement Backend for Notification Settings

src/Hng.Application/Features/EmailTemplates/Handlers/GetAllEmailTemplatesQueryHandler.cs, src/Hng.Application/Features/EmailTemplates/Queries/GetAllEmailTemplatesQuery.cs, src/Hng.Infrastructure/Migrations/20240731095914_EmailTemplatesIndex.Designer.cs, src/Hng.Infrastructure/Migrations/20240731095914_EmailTemplatesIndex.cs, src/Hng.Infrastructure/Repository/Interface/IRepository.cs, src/Hng.Infrastructure/Repository/Repository.cs, src/Hng.Web/Controllers/EmailTemplateController.cs, src/Hng.Web/appsettings.json
Pagination for email template request.
Add pagination to the requests for all the email templates to improve the performance of the application.
- Created page information parameters in endpoints.
- Added pagination support at the database level — only the requested pages are loaded into memory; this improves the performance of the application.
- Allowed for customisable page sizes in the endpoints.
- 
=> [Feat]: Added pagination to email templates

src/Hng.Application/Features/Products/Dtos/GetProductsQueryParameters.cs, src/Hng.Application/Features/Products/Handlers/GetProductsQueryHandler.cs, src/Hng.Application/Features/Products/Queries/GetProductsQuery.cs, src/Hng.Application/Hng.Application.csproj, src/Hng.Web/Controllers/ProductController.cs
**Closes #202 **
Implement Get All Product (Paginated)
=> feat: get all product implemented

src/Hng.Domain/Entities/Role.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/20240801092434_Roles.Designer.cs, src/Hng.Infrastructure/Migrations/20240801092434_Roles.cs, src/Hng.Web/Program.cs
Allow for swagger to be available outside development environment 
=> chore(Documentation): Make swagger accessible outside dev environment

src/Hng.Application.Test/Features/Products/GetProductByNameQueryShould.cs, src/Hng.Application/Features/Products/Handlers/GetProductByNameQueryHandler.cs, src/Hng.Application/Features/Products/Queries/GetProductByNameQuery.cs, src/Hng.Application/Hng.Application.csproj, src/Hng.Web/Controllers/ProductController.cs
**Closes #210**
Create an endpoint to search and filter products by name.
GET endpoint at /api/v1/products/name
Accept 'product_name' as a query parameter
Implement authorization
Return a list of ProductDto objects
Use CQRS pattern with MediatR
Implement proper error handling
=>   [Feat] Implement Product Search and Filter by Name

src/Hng.Web/Controllers/OrganizationController.cs
Fix route definition of the roles endpoint 
** Closes #136 **
- create role feature
- get roles by organization feature
- get role by id feature
- - grant role to organisation members
Provide support for roles and permissions 
- remove repeated resource name from route
=> fix(roles&permissions): fix repeated route resource name for roles endpoints

src/Hng.Application/Features/Organisations/Handlers/GetUsersOrganizationsHandler.cs, src/Hng.Application/Features/Organisations/Queries/GetAllUsersOrganizationsQuery.cs, src/Hng.Application/Features/UserManagement/Handlers/GoogleLoginCommandHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/LoginUserCommandHandler.cs, src/Hng.Application/Features/UserManagement/Mappers/UserMappingProfile.cs, src/Hng.Domain/Entities/User.cs, src/Hng.Web/Controllers/OrganizationController.cs
This Pull Request Fixes Inconsistencies  in access_token position in google auth and login responses,and handles errors in google auth payload mapping
- add mapper for payload to user Entity
- correct position of access_token in response body
- fix google Auth 
- add mapper for payload to user Entity
- correct position of access_token in response body
=> fix(Authentication): fix google auth | fix access_token position

src/Hng.Application/Features/UserManagement/Handlers/GoogleLoginCommandHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/UserSignUpCommandHandler.cs
This Pull Request allows for organisations to be created for a user upon registration through google auth or regular signup
Addresses #228 and #125 
- create organisation based on user details
- Link organisation to created user
- fix google Auth 
- fix organisation creation
- create organisation based on user details
- Link organisation to created user
=> chore(authentication): enable user organisation creation upon registration in google auth and regular signup

docker-compose.prod.yml
=> fix: docker-compose.prod.yml

src/Hng.Application.Test/Features/HelpCenter/CreateHelpCenterTopicCommandShould.cs, src/Hng.Application.Test/Features/HelpCenter/DeleteHelpCenterTopicCommandShould.cs, src/Hng.Application.Test/Features/HelpCenter/GetAllHelpCenterTopicsQueryShould.cs, src/Hng.Application.Test/Features/HelpCenter/GetHelpCenterTopicByIdQueryShould.cs, src/Hng.Application.Test/Features/HelpCenter/HelpCenterTopicsTestsSetup.cs, src/Hng.Application.Test/Features/HelpCenter/SearchHelpCenterTopicsQueryShould.cs, src/Hng.Application.Test/Features/HelpCenter/UpdateHelpCenterTopicCommandShould.cs, src/Hng.Application/Features/HelpCenter/Command/CreateHelpCenterTopicCommand.cs, src/Hng.Application/Features/HelpCenter/Command/DeleteHelpCenterTopicCommand.cs, src/Hng.Application/Features/HelpCenter/Command/UpdateHelpCenterTopicCommand.cs, src/Hng.Application/Features/HelpCenter/Dtos/CreateHelpCenterTopicRequestDto.cs, src/Hng.Application/Features/HelpCenter/Dtos/HelpCenterResponseDto.cs, src/Hng.Application/Features/HelpCenter/Dtos/HelpCenterTopicResponseDto.cs, src/Hng.Application/Features/HelpCenter/Dtos/SearchHelpCenterTopicsRequestDto.cs, src/Hng.Application/Features/HelpCenter/Dtos/UpdateHelpCenterTopicRequestDto.cs, src/Hng.Application/Features/HelpCenter/Handler/CreateHelpCenterTopicCommandHandler.cs, src/Hng.Application/Features/HelpCenter/Handler/DeleteHelpCenterTopicCommandHandler.cs, src/Hng.Application/Features/HelpCenter/Handler/GetHelpCenterTopicByIdQueryHandler.cs, src/Hng.Application/Features/HelpCenter/Handler/GetHelpCenterTopicsQueryHandler.cs, src/Hng.Application/Features/HelpCenter/Handler/SearchHelpCenterTopicsQueryHandler.cs, src/Hng.Application/Features/HelpCenter/Handler/UpdateHelpCenterTopicCommandHandler.cs, src/Hng.Application/Features/HelpCenter/Mappers/HelpCenterTopicMappingProfile.cs, src/Hng.Application/Features/HelpCenter/Queries/GetHelpCenterTopicByIdQuery.cs, src/Hng.Application/Features/HelpCenter/Queries/GetHelpCenterTopicsQuery.cs, src/Hng.Application/Features/HelpCenter/Queries/SearchHelpCenterTopicsQuery.cs, src/Hng.Domain/Entities/HelpCenterTopic.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/20240808184539_HelpCenterTopic.Designer.cs, src/Hng.Infrastructure/Migrations/20240808184539_HelpCenterTopic.cs, src/Hng.Web/Controllers/HelpCenterTopicController.cs
- **Implement CRUD and Search functionalities for Help Center Topics**
1. Implement Full Endpoints for Help Center Topics:
- Create endpoints for managing Help Center topics, including creating, updating, deleting, and searching topics.
2. Define Response Types:
- Ensure the response types for CRUD operations and search are aligned with the provided specifications.
3. Update Mappings and DTOs:
- Ensure that all necessary DTOs and mappings are properly defined and used for handling requests and responses.
4. Write Unit Tests:
- Develop unit tests to cover all the new functionalities (CRUD operations and search).
5. Address Specific Issues:
- Resolve any issues in the existing code or tests, such as incorrect status codes or null values in responses.
- Added …
=> feat(HelpCenter):Implement CRUD and Search functionalities for Help Center Topics

src/Hng.Application.Test/Features/UserManagement/GoogleLoginCommandHandlerTests.cs, src/Hng.Application.Test/Features/UserManagement/LoginUserCommandShould.cs, src/Hng.Application.Test/Features/UserManagement/UserSignUpCommandShould.cs, src/Hng.Application/Features/Organisations/Dtos/OrganizationDto.cs, src/Hng.Application/Features/UserManagement/Commands/CreateUserLoginCommand.cs, src/Hng.Application/Features/UserManagement/Commands/GoogleLoginCommand.cs, src/Hng.Application/Features/UserManagement/Dtos/OrganisationDto.cs, src/Hng.Application/Features/UserManagement/Dtos/SignUpResponse.cs, src/Hng.Application/Features/UserManagement/Dtos/UserLoginResponseDto.cs, src/Hng.Application/Features/UserManagement/Dtos/UserResponseDto.cs, src/Hng.Application/Features/UserManagement/Dtos/UserSignUpDto.cs, src/Hng.Application/Features/UserManagement/Handlers/GoogleLoginCommandHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/LoginUserCommandHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/UserSignUpCommandHandler.cs, src/Hng.Application/Features/UserManagement/Mappers/UserMappingProfile.cs, src/Hng.Domain/Entities/User.cs, src/Hng.Infrastructure/Migrations/20240811002215_AddSuperAdminColumn.Designer.cs, src/Hng.Infrastructure/Migrations/20240811002215_AddSuperAdminColumn.cs, src/Hng.Web/Controllers/AuthenticationController.cs
Change Response signup Login
Tofixtheresponsebodyoftheauthcontroller
- Added mapping for Organization to OrganizationDto in UserMappingProfile.
- Mapped the list of organizations in UserResponseDto.
- Fixed the response body for the signup feature to ensure proper data structure and mappings.
=> fix: Updated UserResponseDto mapping to include organizations

src/Hng.Application.Test/Features/OrganizationInvite/CreateOrganizationInviteShould.cs, src/Hng.Application/Features/OrganisationInvite/Commands/CreateOrganizationInviteCommand.cs, src/Hng.Application/Features/OrganisationInvite/Dtos/CreateOrganizationInviteDto.cs, src/Hng.Application/Features/OrganisationInvite/Dtos/OrganizationInviteDto.cs, src/Hng.Application/Features/OrganisationInvite/Handlers/CreateOrganizationInviteCommandHandler.cs, src/Hng.Application/Features/OrganisationInvite/Mappers/OrganizationInviteMapperProfile.cs, src/Hng.Application/Shared/Dtos/StatusCodeResponse.cs, src/Hng.Domain/Entities/OrganizationInvite.cs, src/Hng.Domain/Enums/OrganizationInviteStatus.cs, src/Hng.Infrastructure/ConfigureInfrastructure.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/20240811002137_OrganisationInvites.Designer.cs, src/Hng.Infrastructure/Migrations/20240811002137_OrganisationInvites.cs, src/Hng.Infrastructure/Services/Interfaces/IOrganisationInviteService.cs, src/Hng.Infrastructure/Services/OrganisationInviteService.cs, src/Hng.Infrastructure/Utilities/Error.cs, src/Hng.Infrastructure/Utilities/Errors/OrganisationInvite/ImplicitErrorOperator.cs, src/Hng.Infrastructure/Utilities/Errors/OrganisationInvite/InviteAlreadyExistsError.cs, src/Hng.Infrastructure/Utilities/Errors/OrganisationInvite/OrganisationDoesNotExistError.cs, src/Hng.Infrastructure/Utilities/Errors/OrganisationInvite/UserIsNotOwnerError.cs, src/Hng.Infrastructure/Utilities/Result.cs, src/Hng.Web/Controllers/OrganizationController.cs, src/Hng.Web/Controllers/TimezoneController.cs, src/Hng.Web/Controllers/TimezonesController.cs, src/Hng.Web/appsettings.json
Creation of invite links for an organisation.
**Closes #102**
Allow the owner of an organisation the ability to generate unique invite links which allow individuals to join the organisation.
- Implemented a new feature to support creating organization invites.
- Introduced a pattern for handling operation results and errors.
- Enhanced error handling to provide appropriate HTTP responses without using exceptions.
=> feat: create invite links to join an organisation

src/Hng.Application.Test/Features/Products/CreateProductShould.cs, src/Hng.Application.Test/Features/Products/GetAllProductsShould.cs, src/Hng.Application/Features/Products/Dtos/CreateProductResponseDto.cs, src/Hng.Application/Features/Products/Dtos/ProductResponseDto.cs, src/Hng.Application/Features/Products/Handlers/GetAllProductsHandler.cs, src/Hng.Application/Features/Products/Mappers/ProductMapperProfile.cs, src/Hng.Application/Features/Products/Queries/GetAllProductsQuery.cs, src/Hng.Web/Controllers/ProductController.cs
Create endpoint that allows users with admin role view all products in their organisation
The route of the endpoint should be:
GET /api/v1/:org_id/products (Protected admin route) Retrieve all organisation's products
The response body should be:
{
"status_code": 200,
"message": "Product retrieved successfully",
"data": {
"products": [
{
"id": "9cc529fc-85a8-4012-bf5b-f3954be214a9",
"created_at": "2024-08-08T18:07:00.728Z",
"updated_at": "2024-08-08T18:07:00.728Z",
"name": "Product 1",
"description": "Description for Product 1",
"category": "electricity",
"image": null,
"price": 500,
"cost_price": 0,
"quantity": 1,
"size": "Standard",
"stock_status": "out of stock",
"deletedAt": null
},
{
"id": "4927ef54-707b-417e-a469-bad05deb904d",
"created_at": …
=> feat(product): Get all product for admin

src/Hng.Infrastructure/Services/SeederService.cs
This Pr repairs the error thrown by the seeder service when faking Product Entities
**Closes #63 **
- add organisation to product seeder
=> fix(Products): fix seeder service error when seeding product entities

src/Hng.Application.Test/Features/UserManagement/GoogleLoginCommandHandlerTests.cs, src/Hng.Application.Test/Features/UserManagement/LoginUserCommandShould.cs, src/Hng.Application/Features/UserManagement/Handlers/GoogleLoginCommandHandler.cs
Fix: Resolve Issues in Google Login and Login Command Handlers
- Fixed NullReferenceException in GoogleLoginCommandHandler by ensuring proper user data handling and mock setup.
- Corrected test for LoginUserCommandHandler to address failures related to valid credentials by adjusting mock expectations and test data.
- Improved error handling and validation in both handlers to ensure accurate response messages and token generation.
=> Fix: Resolve Issues in GoogleLoginCommandShould and LoginLoginCommandShould

src/Hng.Application.Test/Features/UserManagement/GoogleLoginCommandHandlerTests.cs, src/Hng.Application.Test/Features/UserManagement/LoginUserCommandShould.cs
Reverts hngprojects/hng_boilerplate_csharp_web#277
Test still fails
=> Revert "Fix: Resolve Issues in GoogleLoginCommandShould and LoginLoginCommandShould"

src/Hng.Application.Test/Features/Profile/UpdateProfileHandlerShould.cs, src/Hng.Application.Test/Features/Profile/UpdateProfilePictureHandlerShould.cs, src/Hng.Application.Test/Features/UserManagement/GoogleLoginCommandHandlerTests.cs, src/Hng.Application.Test/Features/UserManagement/LoginUserCommandShould.cs, src/Hng.Application/Features/Profiles/Handlers/UpdateProfileHandler.cs, src/Hng.Application/Features/Profiles/Handlers/UpdateProfilePictureHandler.cs, src/Hng.Application/Features/UserManagement/Dtos/UserResponseDto.cs, src/Hng.Application/Features/UserManagement/Handlers/GoogleLoginCommandHandler.cs
Changes allow someone to upload picture even when he does not have other credentails, also fix test failure
To allow users update picture even when other details are empty
allowed users update picture even when other details are empty
=> chore(profile picture): made some changes in profile picture update

src/Hng.Application.Test/Features/Notifications/DeleteAllNotificationsCommandHandlerShould.cs, src/Hng.Application.Test/Features/Notifications/DeleteNotificationByIdCommandHandlerShould.cs, src/Hng.Application/Features/Notifications/Commands/DeleteAllNotificationsCommand.cs, src/Hng.Application/Features/Notifications/Commands/DeleteNotificationByIdCommand.cs, src/Hng.Application/Features/Notifications/Handlers/DeleteAllNotificationsCommandHandler.cs, src/Hng.Application/Features/Notifications/Handlers/DeleteNotificationByIdCommandHandler.cs, src/Hng.Web/Controllers/NotificationController.cs
This PR introduces two endpoints for deleting notifications for authenticated users. The first endpoint allows clearing all notifications, while the second allows deleting a specific notification by its ID.
Features Implemented:
- Delete All Notifications: Provides a method to clear all notifications for the authenticated user.
- Delete Single Notification: Allows deleting a specific notification by its ID.
- Authentication: Ensures that only authenticated users can delete their notifications.
- Error Handling: Manages errors for unauthenticated users, invalid requests, and other issues.
1. Delete All Notifications
Endpoint: DELETE /api/v1/notifications/clear-all
Summary: Clear all notifications for the authenticated user.
Successful Response:
Status Code: …
=> feat(notification): clear notifications

src/Hng.Application.Test/Features/Dashboard/GetDashboardQueryShould.cs, src/Hng.Application/Features/Dashboard/Dtos/DashboardDto.cs, src/Hng.Application/Features/Dashboard/Handlers/GetDashboardQueryHandler.cs, src/Hng.Application/Features/Dashboard/Mappers/DashboardMapperProfile.cs, src/Hng.Application/Features/Dashboard/Queries/GetDashboardQuery.cs, src/Hng.Web/Controllers/DashboardsController.cs
**Closes #281 
I developed an API endpoint to fetch data for the dashboard overview, including total revenue, number of subscriptions/subscribers, sales, number of active subscribers now, and recent sales.
=> Implement Dashboard Overview API

src/Hng.Application/Features/UserManagement/Dtos/SwitchOrganisationResponseDto.cs, src/Hng.Application/Features/UserManagement/Handlers/SwitchOrganisationCommandHandler.cs
Fixed the relevant responses and status codes.
=> refactor: organisation - refactored responses and status codes.

src/Hng.Application.Test/Features/UserManagement/SwitchOrganisationCommandShould.cs, src/Hng.Application/Features/UserManagement/Handlers/SwitchOrganisationCommandHandler.cs
Fixed failing tests for status codes
=> fix: fixed failing test for status codes

src/Hng.Application.Test/Features/Dashboard/GetSalesTrendQueryShould.cs, src/Hng.Application/Features/Dashboard/Dtos/SalesTrendQueryParameter.cs, src/Hng.Application/Features/Dashboard/Handlers/GetSalesTrendQueryHandler.cs, src/Hng.Application/Features/Dashboard/Queries/GetSalesTrendQuery.cs, src/Hng.Web/Controllers/DashboardsController.cs
**Closes #287 
I implement the backend logic to aggregate and provide sales data for the dashboard's sales trend visualization. And also create API endpoints to fetch the sales data, including date ranges and sales figures.
=> [FEAT] Sales Trend Data Integration

src/Hng.Application.Test/Features/Dashboard/GetNavigationDataQueryShould.cs, src/Hng.Application.Test/Features/Dashboard/GetSalesTrendQueryShould.cs, src/Hng.Application/Features/Dashboard/Dtos/NavigationDataDto.cs, src/Hng.Application/Features/Dashboard/Handlers/GetNavigationDataQueryHandler.cs, src/Hng.Application/Features/Dashboard/Queries/GetNavigationDataQuery.cs, src/Hng.Web/Controllers/DashboardsController.cs
**Closes #290 
I implement backend logic to support the different sections of the dashboard (Overview, Analysis, Reports). And ensure that data for each section is fetched and prepared accurately for display.
=> Feat(Dashboard): Navigation Section Data Handling

src/Hng.Application/Features/Faq/Dtos/CreateFaqResponseDto.cs, src/Hng.Application/Features/Faq/Dtos/UpdateFaqResponseDto.cs, src/Hng.Application/Features/Faq/Handlers/CreateFaqCommandHandler.cs, src/Hng.Application/Features/Faq/Handlers/UpdateFaqCommandHandler.cs, src/Hng.Application/Features/Faq/Mappers/FaqMappingProfile.cs, src/Hng.Domain/Entities/Faq.cs, src/Hng.Infrastructure/Migrations/20240814190933_faqUpdatedClass.Designer.cs, src/Hng.Infrastructure/Migrations/20240814190933_faqUpdatedClass.cs, src/Hng.Web/Controllers/FaqController.cs
- Add API documentation for FaqController and refactor endpoints.
- Added XML documentation comments for the FaqController actions to ensure consistency with the AuthenticationController.
- Updated endpoints to include proper response types and status codes.
=> Feat(Faq): API documentation for FaqController and refactor endpoints

src/Hng.Application.Test/Features/Blog/CreateBlogCommandShould.cs, src/Hng.Application.Test/Features/Blog/UpdateBlogCommandShould.cs, src/Hng.Application.Test/Features/UserManagement/SwitchOrganisationCommandShould.cs, src/Hng.Application/Features/Blogs/Commands/CreateBlogCommand.cs, src/Hng.Application/Features/Blogs/Commands/UpdateBlogCommand.cs, src/Hng.Application/Features/Blogs/Dtos/CreateBlogResponseDto.cs, src/Hng.Application/Features/Blogs/Dtos/UpdateBlogResponseDto.cs, src/Hng.Application/Features/Blogs/Handlers/CreateBlogCommandHandler.cs, src/Hng.Application/Features/Blogs/Handlers/UpdateBlogCommandHandler.cs, src/Hng.Application/Features/UserManagement/Commands/SwitchOrganisationCommand.cs, src/Hng.Application/Features/UserManagement/Dtos/SwitchOrganisationResponseDto.cs, src/Hng.Application/Features/UserManagement/Handlers/SwitchOrganisationCommandHandler.cs
Fixed request and response bodies `(for create and update blog)` to meet standards
=> fix: fix request and response bodies to meet standards

src/Hng.Application.Test/Features/Roles/CreateRoleCommandShould.cs, src/Hng.Application.Test/Features/Roles/GetRoleByIdQueryShould.cs, src/Hng.Application.Test/Features/Roles/GetRolePermissionsQueryShould.cs, src/Hng.Application.Test/Features/UserManagement/GoogleLoginCommandHandlerTests.cs, src/Hng.Application.Test/Features/UserManagement/LoginUserCommandShould.cs, src/Hng.Application/Features/Roles/Command/CreateRoleCommand.cs, src/Hng.Application/Features/Roles/Command/GetRolePermissionsQuery.cs, src/Hng.Application/Features/Roles/Dto/CreateRoleRequestDto.cs, src/Hng.Application/Features/Roles/Dto/CreateRoleResponseDto.cs, src/Hng.Application/Features/Roles/Dto/RoleDetailsResponseDto.cs, src/Hng.Application/Features/Roles/Handler/CreateRoleCommandHandler.cs, src/Hng.Application/Features/Roles/Handler/GetRoleByIdQueryHandler.cs, src/Hng.Application/Features/Roles/Handler/GetRolePermissionsQueryHandler.cs, src/Hng.Application/Features/Roles/Mappers/RoleMappingProfile.cs, src/Hng.Application/Features/Roles/Queries/GetRoleByIdQuery.cs, src/Hng.Application/Features/Roles/Queries/GetRolePermissionsQuery.cs, src/Hng.Application/Features/UserManagement/Handlers/GoogleLoginCommandHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/LoginUserCommandHandler.cs, src/Hng.Application/Shared/Dtos/FailureResponseDto.cs, src/Hng.Application/Shared/Dtos/SuccessResponseDto.cs, src/Hng.Domain/Entities/RolePermission.cs, src/Hng.Domain/EntitiesConfigurations/RolePermissionConfig.cs, src/Hng.Infrastructure/Migrations/20240814204322_ManyToManyPermissions.Designer.cs, src/Hng.Infrastructure/Migrations/20240814204322_ManyToManyPermissions.cs, src/Hng.Infrastructure/Repository/Repository.cs, src/Hng.Infrastructure/Services/SeederService.cs, src/Hng.Web/Controllers/AuthenticationController.cs, src/Hng.Web/Controllers/OrganizationController.cs, src/Hng.Web/Extensions/MigrateAndSeedExtension.cs
This Pr Exposes and fixes the User role Permission feature 
**Closes #136 **
- make permissions many to many relationship
- Write test for get all permissions
- Expose get all permissions endpoint
- write tests for get all permissions
- edit create role handler to support permissions
=> feat(permissions): Set up User Role Permissions, expose get all permissions endpoint

src/Hng.Application/Features/HelpCenter/Dtos/HelpCenterTopicResponseDto.cs, src/Hng.Application/Features/HelpCenter/Handler/CreateHelpCenterTopicCommandHandler.cs, src/Hng.Application/Features/HelpCenter/Handler/DeleteHelpCenterTopicCommandHandler.cs, src/Hng.Application/Features/HelpCenter/Handler/SearchHelpCenterTopicsQueryHandler.cs, src/Hng.Application/Features/HelpCenter/Handler/UpdateHelpCenterTopicCommandHandler.cs, src/Hng.Application/Features/HelpCenter/Mappers/HelpCenterTopicMappingProfile.cs, src/Hng.Web/Controllers/HelpCenterTopicController.cs
-  Add documentation and standardize response handling in HelpCenterTopicController
- implement documentation and standardize response handling in HelpCenterTopicController.
- Added XML comments to all endpoints in HelpCenterTopicController for better clarity.
- Standardized response types using ProducesResponseType attribute.
- Refined route and parameter attributes for better URL structure and GUID enforcement.
=> Feat: Add documentation in HelpCenterTopicController

src/Hng.Application/Features/Organisations/Commands/CreateOrganizationCommand.cs, src/Hng.Application/Features/Organisations/Dtos/GetOrganisationResponseDto.cs, src/Hng.Application/Features/Organisations/Dtos/OrganizationDto.cs, src/Hng.Application/Features/Organisations/Handlers/GetOrganizationByIdQueryHandler.cs, src/Hng.Application/Features/Organisations/Queries/GetOrganizationByIdQuery.cs
Fixed issues with get organisation by id response
=> fix: organisation - fix issues with get organisation by id response

src/Hng.Application/Shared/Dtos/EmptyDataResponse.cs, src/Hng.Web/Controllers/OrganizationController.cs
=> feat: move invite links path to match standards

src/Hng.Web/ModelStateError/ModelError.cs, src/Hng.Web/ModelStateError/ModelStateErrorResponse.cs, src/Hng.Web/Program.cs
This PR addresses the issue of the errors generated by ASP.NET's model-state validation not aligning with the recommended standard for all HNG boilerplate backends.
Modify the error responses generated by the model-state validation to conform with the standards for all HNG Boilerplate backends.
- Created custom error objects.
- Created a custom model-state response factory.
- Configured the response factory to override the default factory for validation errors.
- 
=> feat: modify model-state error responses to conform to API standards

src/Hng.Application.Test/Features/Dashboard/GetExportDataQueryShould.cs, src/Hng.Application.Test/Features/Dashboard/GetNavigationDataQueryShould.cs, src/Hng.Application/Features/Dashboard/Handlers/GetExportDataQueryHandler.cs, src/Hng.Application/Features/Dashboard/Queries/GetExportDataQuery.cs, src/Hng.Web/Controllers/DashboardsController.cs
**Closes #304 
I Develop the backend functionality to support downloading the dashboard overview data in various formats (e.g., CSV, PDF).
And also ensure that the data is exported accurately and promptly
=> [Feat] Implement Download Functionality for Dashboard Overview

src/Hng.Application.Test/Features/Roles/AssignRolesCommandShould.cs, src/Hng.Application.Test/Features/UserManagement/GetCurrentlyLoggedInUserDetailsShould.cs, src/Hng.Application.Test/Features/UserManagement/GetUserByIdQueryShould.cs, src/Hng.Application/Features/Roles/Command/AssignRoleCommand.cs, src/Hng.Application/Features/Roles/Dto/AssignRoleDto.cs, src/Hng.Application/Features/Roles/Handler/AssignRoleCommandHandler.cs, src/Hng.Application/Features/UserManagement/Dtos/UserDto.cs, src/Hng.Application/Features/UserManagement/Handlers/GetLoggedInUserDetailsQueryHandler.cs, src/Hng.Application/Features/UserManagement/Mappers/UserMappingProfile.cs, src/Hng.Application/Features/UserManagement/Queries/GetLoggedInUserDetailsQuery.cs, src/Hng.Web/Controllers/AuthenticationController.cs, src/Hng.Web/Controllers/OrganizationController.cs
This Pr exposes Features for assigning roles to members of an Organization and an endpoint to get details of curently logged in user
**Closes #136 **
- expose /auth/@me endpoint
- assign roles to users in organization
- expose endpoint for assingning these users
- write tests for their handlers
- implement /api/v1/auth/@me
- get details of currrently logged in user
- expose route to assign user to roles in an organization
- Write tests for their command handlers
=> fea(getuserdetails&AssignRole): expose assign role endpoint | get details of currently liogged in user

src/Hng.Application/Features/UserManagement/Dtos/ForgotPasswordDto.cs, src/Hng.Application/Features/UserManagement/Dtos/PasswordResetMobileDto.cs, src/Hng.Application/Features/UserManagement/Dtos/VerifyForgotPasswordCodeDto.cs, src/Hng.Application/Features/UserManagement/Handlers/ForgotPasswordHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/PasswordResetMobileHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/VerifyForgotPasswordCodeHandler.cs, src/Hng.Infrastructure/EmailTemplates/forgot-password-mobile.html, src/Hng.Infrastructure/Services/EmailTemplateService.cs, src/Hng.Infrastructure/Services/Interfaces/IEmailTemplateService.cs, src/Hng.Infrastructure/Services/Interfaces/IMessageQueueService.cs, src/Hng.Infrastructure/Services/MessageQueueService.cs, src/Hng.Infrastructure/Utilities/StringKeys/EmailConstants.cs, src/Hng.Web/Controllers/AuthenticationController.cs
Added endpoint for forgot and reset passwords and verify Code.
Add endpoint for Forgot and Reset password, and Verify Code
Added endpoint for Forgot and Reset password, and verify Code
=> feat(forgot-password): added forgot-password and reset password endpoint for Mobile

src/Hng.Web/Controllers/AuthenticationController.cs
I was passing wrong response objects on my endpoints
=> chore(forgot-password): clean up controller responses 

src/Hng.Application.Test/Features/Organization/GetAllUsersQueryHandlerShould.cs, src/Hng.Application/Features/Organisations/Dtos/OrganizationUserDto.cs, src/Hng.Application/Features/Organisations/Handlers/GetAllUsersQueryHandler.cs, src/Hng.Application/Features/Organisations/Mappers/OrganizationMapperProfile.cs, src/Hng.Application/Features/Organisations/Queries/GetAllUsersQuery.cs, src/Hng.Application/Features/UserManagement/Dtos/UserOrganzationDto.cs, src/Hng.Application/Features/UserManagement/Mappers/UserMappingProfile.cs, src/Hng.Web/Controllers/OrganizationController.cs
This PR introduces an endpoint for retrieving all users within a specific organization for authenticated users. This endpoint allows fetching user details associated with a given organization ID.
Features Implemented:
- Retrieve Organization Users: Provides a method to fetch all users belonging to a specific organization.
- Authentication: Ensures that only authenticated users can access the organization's user list.
- Error Handling: Manages errors for cases where the organization is not found or other issues occur.
Endpoint: GET /api/v1/organizations/{orgId}/users
Summary: Retrieve all users associated with a specific organization.
- orgId (required, Guid) - The ID of the organization to fetch users from.
Successful Response:
Status Code: 200 OK
Response: …
=> feat(organization): Get all organization users

src/Hng.Application.Test/Features/OrganizationInvite/CreateAndSendInvitesCommandHandlerShould.cs, src/Hng.Application/Features/OrganisationInvite/Commands/AcceptInviteCommand.cs, src/Hng.Application/Features/OrganisationInvite/Handlers/AcceptInviteCommandHandler.cs, src/Hng.Application/Features/OrganisationInvite/Handlers/CreateAndSendInvitesCommandHandler.cs, src/Hng.Application/Features/OrganisationInvite/Handlers/GetUniqueOrganisationInviteLinkQueryHandler.cs, src/Hng.Application/Shared/Dtos/Validators/EmailCollectionAttribute.cs, src/Hng.Domain/Entities/OrganizationInvite.cs, src/Hng.Infrastructure/Migrations/20240817112410_OrganisationInviteGuidCode.Designer.cs, src/Hng.Infrastructure/Migrations/20240817112410_OrganisationInviteGuidCode.cs, src/Hng.Infrastructure/Services/Interfaces/IOrganisationInviteService.cs, src/Hng.Infrastructure/Services/MessageQueueService.cs, src/Hng.Infrastructure/Services/OrganisationInviteService.cs
This PR fixes a number of issues with invite links:
- Improper logging of invitation requests.
- Wrong invitation links generated for the unique organisation links.
- Potential duplicate use of email invites.
- Coupling of saved invites to the frontend url — fixed by only using the GUID invite code.
Fix multiple issues with the invite links including: 
- Duplicate use of email invites.
- Invalid links being generated by the application.
- Coupling between the invites saved in the db and the FE url.
- Made the email invites one-use.
- Stripped the FE url from the db records.
- Fixed the generated unique organisation link.
- Corrected and removed duplicate application logs.
- Created the backing methods, commands, and handlers to enable the above.
🚨Please review the [contribution …
=> fix: fixes for invitations 

src/Hng.Infrastructure/Repository/Repository.cs
=> feat: newly created user is added to the organisation if they are invited

src/Hng.Application/Features/UserManagement/Dtos/ChangePasswordCommand.cs, src/Hng.Application/Features/UserManagement/Dtos/PasswordResetDto.cs, src/Hng.Application/Features/UserManagement/Dtos/PasswordResetMobileDto.cs, src/Hng.Application/Features/UserManagement/Handlers/PasswordResetHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/VerifyForgotPasswordCodeHandler.cs
Updated the requests body to snake case
=> chore(forgot-password): change request body to snake case

src/Hng.Application.Test/Features/Roles/UpdateRoleCommandShould.cs, src/Hng.Application/Features/Roles/Command/UpdateRoleCommand.cs, src/Hng.Application/Features/Roles/Dto/UpdateRoleRequestDto.cs, src/Hng.Application/Features/Roles/Dto/UpdateRoleResponseDto.cs, src/Hng.Application/Features/Roles/Handler/UpdateRoleCommandHandler.cs, src/Hng.Web/Controllers/OrganizationController.cs
This Pull Request Includes updates to the update role feature, allowing permissions to also be updated when updating a role
**Closes #214 **
- update Update Role request Dto
- update commend handler to handle permissions 
- Update tests to follow changes to the command handler
- Update test to support new feature
- update update role command handler to update permissions as well
- Update response body 
=> feat(Roles$permissions): Allow updating permissions when updating a role

src/Hng.Application/Features/LastLoginUser/Command/LogoutCommand.cs, src/Hng.Application/Features/LastLoginUser/Handlers/LogoutCommandHandler.cs, src/Hng.Web/Controllers/LastLoginController.cs
- Update logout endpoint to handle and return a list of user login sessions
Createalogoutendpoint
- Updated LogoutCommandHandler to process and update multiple login sessions for a user.
- Added mapping of multiple LastLogin entities to a list of LastLoginDto.
- Ensured proper handling and response formatting for cases where no active login sessions are found.
=> feat: Update logout endpoint .

src/Hng.Application/Features/LastLoginUser/Command/LogoutCommand.cs, src/Hng.Application/Features/LastLoginUser/Handlers/LogoutCommandHandler.cs, src/Hng.Web/Controllers/LastLoginController.cs
Reverts hngprojects/hng_boilerplate_csharp_web#326
=> Revert "Revert "feat: Update logout endpoint .""

src/Hng.Application.Test/Features/UserManagement/FacebookLoginCommandShould.cs, src/Hng.Application.Test/Features/UserManagement/UserSignUpCommandShould.cs, src/Hng.Application/ConfigureApplication.cs, src/Hng.Application/Features/UserManagement/Dtos/ChangePasswordCommand.cs, src/Hng.Application/Features/UserManagement/Dtos/ForgotPasswordDto.cs, src/Hng.Application/Features/UserManagement/Dtos/PasswordResetDto.cs, src/Hng.Application/Features/UserManagement/Dtos/UserDto.cs, src/Hng.Application/Features/UserManagement/Dtos/VerifyForgotPasswordCodeDto.cs, src/Hng.Application/Features/UserManagement/Handlers/ChangePasswordHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/ForgotPasswordHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/LoginUserCommandHandler.cs, src/Hng.Application/Features/UserManagement/Handlers/PasswordResetHandler.cs, src/Hng.Infrastructure/EmailTemplates/forgot-password.html, src/Hng.Infrastructure/Services/Interfaces/ITokenService.cs, src/Hng.Infrastructure/Services/TokenService.cs, src/Hng.Infrastructure/Utilities/Jwt.cs, src/Hng.Web/Controllers/AuthenticationController.cs
Ndubisi adviced a better way to handle forgot and reset password for FE, that's what this PR is for
=> chore (reset-password) - Make changes to reset and forgot password for FE

.github/workflows/dev-deployment.yml, .github/workflows/production-deployment.yml, .github/workflows/staging-deployment.yml, docker-compose.prod.yml, docker-compose.staging.yml, docker-compose.yml
I added updated docker-related files, and I updated our CI/CD workflow to work with the new setup.
=> ci: dockerization

src/Hng.Application/Features/Subscriptions/Handlers/ActivateSubscriptionCommandHandler.cs
The PR fixes error encountered in activating subscription 
=> fix: fixed activate subscription

src/Hng.Application.Test/Features/Profile/UpdateProfileHandlerShould.cs, src/Hng.Application.Test/Features/Profile/UpdateProfilePictureHandlerShould.cs, src/Hng.Application/Features/Profiles/Dtos/DeleteProfilePictureDto.cs, src/Hng.Application/Features/Profiles/Dtos/UpdateProfile.cs, src/Hng.Application/Features/Profiles/Dtos/UpdateProfilePictureDto.cs, src/Hng.Application/Features/Profiles/Handlers/DeleteProfileHandler.cs, src/Hng.Application/Features/Profiles/Handlers/UpdateProfileHandler.cs, src/Hng.Application/Features/Profiles/Handlers/UpdateProfilePictureHandler.cs, src/Hng.Web/Controllers/AuthenticationController.cs, src/Hng.Web/Controllers/ProfileController.cs
Did cleanup around profile update.
I remove the email I passed as path parameter but rather pick it from login user
=> chore: remove email from profile(picture) update

src/Hng.Application/Features/ApiStatuses/Dtos/Requests/UpdateApiStatusDto.cs, src/Hng.Application/Features/ApiStatuses/Dtos/Responses/ApiStatusResponseDto.cs, src/Hng.Application/Features/ApiStatuses/Handlers/Commands/UpdateApiStatusHandler.cs, src/Hng.Application/Features/ApiStatuses/Handlers/Queries/FetchApiStatusesHandler.cs, src/Hng.Domain/Entities/ApiStatus.cs, src/Hng.Domain/Entities/Category.cs, src/Hng.Domain/Entities/Faq.cs, src/Hng.Domain/Entities/HelpCenterTopic.cs, src/Hng.Domain/Entities/LastLogin.cs, src/Hng.Domain/EntitiesConfigurations/ApiStatusConfiguration.cs, src/Hng.Domain/Enums/ApiStatusType.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/20240823114543_ApiStatusTable.Designer.cs, src/Hng.Infrastructure/Migrations/20240823114543_ApiStatusTable.cs
=> feat: ApiStatus database Configuration

src/Hng.Application.Test/Features/ApiStatuses/GetAllStatusApiQueryShould.cs, src/Hng.Application/Features/ApiStatuses/Dtos/Requests/GetAllApiStatusesQueries.cs, src/Hng.Application/Features/ApiStatuses/Handlers/Queries/GetAllApiStatusesHandler.cs, src/Hng.Application/Features/ApiStatuses/Mappers/ApiStatusesMapperProfile.cs, src/Hng.Web/Controllers/ApiStatusController.cs
- Added GetStatus endpoint to retrieve API statuses with pagination.
- Implemented GetStatusQuery and GetStatusQueryHandler for handling the request.
- Added default pagination handling in GetStatusQueryHandler.
- Created unit tests for GetStatus endpoint using xUnit and Moq.
- Ensured tests cover successful retrieval, empty result scenarios, and error handling.
- Implement GetAllAPIStatusEndpoint.
1. Feature Added: The implementation of the GetStatus endpoint.
2. CQRS Implementation: Use of CQRS with GetStatusQuery and GetStatusQueryHandler.
3. Pagination Handling: Default pagination values in the handler.
4. Testing: Creation and coverage of unit tests.
=> Feat : Implementation GetAllAPIStatus endpoint 

src/Hng.Web/Controllers/DashboardsController.cs
I fixed dashboard isssue for new user
=> fix: fixed dashboard

src/Hng.Application.Test/Features/UserManagement/UserSignUpCommandShould.cs, src/Hng.Application/Features/UserManagement/Handlers/UserSignUpCommandHandler.cs
-  Add email notification on user signup
- Add email notification on user signup
- Integrated email service to send welcome emails after successful user registration.
- Ensured email includes user's name and welcome message.
- Added error handling to log and manage any issues during email sending.
=> feat: Add email notification on user signup

src/Hng.Application/Features/Blogs/Commands/CreateBlogCommand.cs, src/Hng.Application/Features/Blogs/Commands/UpdateBlogCommand.cs
This pr attempts to fix exception thrown when trying to create or update a blog post by correcting the Irequest type inherited by the blog commands
**Closes #177 **
- Fix Blogs 
- Fix inherited request type in create blog command
- Fix inherited request type in update blog command 
=> fix(Blogs): remove incorrect Irequest inheriting response types in blog commands

src/Hng.Application.Test/Features/Contacts/CreateContactUsCommandShould.cs, src/Hng.Application.Test/Features/Contacts/DeleteContactUsCommandShould.cs, src/Hng.Application.Test/Features/Contacts/GetAllContactUsQueryShould.cs, src/Hng.Application/Features/ContactsUs/Command/CreateContactUsCommand.cs, src/Hng.Application/Features/ContactsUs/Command/DeleteContactUsCommand.cs, src/Hng.Application/Features/ContactsUs/Dtos/ContactResponse.cs, src/Hng.Application/Features/ContactsUs/Dtos/ContactUsRequestDto.cs, src/Hng.Application/Features/ContactsUs/Dtos/ContactUsResponseDto.cs, src/Hng.Application/Features/ContactsUs/Handlers/CreateContactUsCommandHandler.cs, src/Hng.Application/Features/ContactsUs/Handlers/DeleteContactUsCommandHandler.cs, src/Hng.Application/Features/ContactsUs/Handlers/GetAllContactUsQueryHandler.cs, src/Hng.Application/Features/ContactsUs/Mappers/ContactUsMappingProfile.cs, src/Hng.Application/Features/ContactsUs/Queries/GetAllContactUsQuery.cs, src/Hng.Domain/Entities/ContactUs.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/20240829072245_ContactUs.Designer.cs, src/Hng.Infrastructure/Migrations/20240829072245_ContactUs.cs, src/Hng.Web/Controllers/ContactUsController.cs
- Implement Contact Us endpoint with unit tests
Implement Contact Us endpoint.
- Added ContactUs endpoint to handle CRUD operations.
- Created GetAllContactUsQueryHandler to retrieve all ContactUs messages.
- Set up AutoMapper profile for ContactUs entity mapping.
- Developed unit tests for the ContactUs endpoint to ensure proper functionality.
=> feat: Implement Contact Us endpoint.

src/Hng.Application/Features/UserManagement/Handlers/ForgotPasswordHandler.cs
… is failing on staging
The forgot password is failing on staging but when debugged locally everything is fine.
Added logs to aid debug why it fails on staging.
=> chore: added logs in Forgot Password Handler to aid Debug

Hng.Csharp.Web.sln, src/Hng.Graphql/ConfigureGraphql.cs, src/Hng.Graphql/Hng.Graphql.csproj, src/Hng.Graphql/Mutations.cs, src/Hng.Graphql/Queries.cs, src/Hng.Web/Hng.Web.csproj, src/Hng.Web/Program.cs
This Pr provides support for graphql with basic setup and Usermanagement and Roles queries and Mutations setup
- Add graphql project
- Add @me and login query and mutation
- 
- Setup project to support graphql
- Implement  a query resolver for @me handler
- Implement a Mutation resolver for login handler
- Setup project to support graphql
- Implement  a query resolver for @me handler
- Implement a Mutation resolver for login handler
- Implement  query resolver for get role by id and get all permissions
- Implement  Mutation for Create Role and Google Login
- Set up Cors
=> feat(graphql): SetUp graphql project | Implement UserManagement and Roles Queries and Mutations

src/Hng.Graphql/Mutations.cs, src/Hng.Graphql/Queries.Dashboard.cs, src/Hng.Graphql/Queries.cs, src/Hng.Web/Controllers/DashboardsController.cs
=> feat: added graphql for dashboard controller

src/Hng.Graphql/Mutations.EmailTemplate.cs, src/Hng.Graphql/Mutations.cs, src/Hng.Graphql/Queries.EmailTemplate.cs, src/Hng.Graphql/Queries.cs
=> feat: added graphql for Email Template controller

src/Hng.Application/Features/Faq/Dtos/CreateFaqResponseDto.cs, src/Hng.Application/Features/Faq/Dtos/DeleteFaqResponseDto.cs, src/Hng.Application/Features/Faq/Dtos/UpdateFaqResponseDto.cs, src/Hng.Application/Features/Faq/Handlers/UpdateFaqCommandHandler.cs, src/Hng.Graphql/Mutations.Faq.cs, src/Hng.Graphql/Mutations.cs, src/Hng.Graphql/Queries.Faq.cs, src/Hng.Graphql/Queries.cs, src/Hng.Web/Controllers/FaqController.cs
=> feat: added graphql for Faq controller 

src/Hng.Application.Test/Features/WaitLists/CreateWaitlistCommandHandlerShould.cs, src/Hng.Application.Test/Features/WaitLists/DeleteWaitlistByIdCommandHandlerShould.cs, src/Hng.Application.Test/Features/WaitLists/GetAllWaitlistQueryHandlerShould.cs, src/Hng.Application/Features/WaitLists/Commands/CreateWaitlistCommand.cs, src/Hng.Application/Features/WaitLists/Commands/DeleteWaitlistByIdCommand.cs, src/Hng.Application/Features/WaitLists/Dtos/WaitListDto.cs, src/Hng.Application/Features/WaitLists/Handlers/CreateWaitlistCommandHandler.cs, src/Hng.Application/Features/WaitLists/Handlers/DeleteWaitlistByIdCommandHandler.cs, src/Hng.Application/Features/WaitLists/Handlers/GetAllWaitlistQueryHandler.cs, src/Hng.Application/Features/WaitLists/Mappers/WaitListMappingProfile.cs, src/Hng.Application/Features/WaitLists/Queries/GetAllWaitlistQuery.cs, src/Hng.Application/Hng.Application.csproj, src/Hng.Domain/Entities/Waitlist.cs, src/Hng.Infrastructure/Context/ApplicationDbContext.cs, src/Hng.Infrastructure/Migrations/20240831001639_Waitlist.Designer.cs, src/Hng.Infrastructure/Migrations/20240831001639_Waitlist.cs, src/Hng.Web/Controllers/WaitlistController.cs
This PR introduces endpoints for managing waitlists, including creating a new waitlist entry, retrieving all waitlist entries, and deleting a waitlist entry by ID.
Features Implemented:
1. Create Waitlist: Allows users to create a new waitlist entry by providing an email address.
2. Get All Waitlists: Retrieves all waitlist entries.
3. Delete Waitlist: Deletes a specific waitlist entry by its ID.
4. Error Handling: Manages errors for invalid requests, existing entries, and unauthorized access.
1. Create Waitlist
- Endpoint: POST /api/v1/waitlists
- Summary: Creates a new waitlist entry with the provided email.
```json
{
"name": "john"
"email": "new@example.com"
}
```
Successful Response:
Status Code: 201 Created
Response:
```json
{
"message": "Waitlist entry …
```
=> feat(waitlist): Add create, get all and delete waitlist by id

.github/workflows/c-sharp-postman-test.yaml
=> Added C-sharp Run Postman Tests

src/Hng.Graphql/Mutations.Categories.cs, src/Hng.Graphql/Queries.Categories.cs
=> Feat: Implement Category Management in Graphql

src/Hng.Graphql/Mutations.BillingPlans.cs, src/Hng.Graphql/Mutations.Blog.cs, src/Hng.Graphql/Queries.Blog.cs
=> Feat: Implement Blog Management in Graphql

src/Hng.Graphql/Mutations.Comment.cs, src/Hng.Graphql/Queries.Comment.cs
=> Feat: Implement Comment Management in Graphql

src/Hng.Graphql/Mutations.ContactUs.cs, src/Hng.Graphql/Queries.ContactUs.cs
=> Feat: Implement Contact Us Endpoints in Graphql

src/Hng.Graphql/Mutations.ContactUs.cs, src/Hng.Graphql/Mutations.Subscriptions.cs, src/Hng.Graphql/Queries.Admin.cs, src/Hng.Graphql/Queries.ContactUs.cs, src/Hng.Graphql/Queries.Subscriptions.cs
=> Implement Admin management in Graphql

src/Hng.Graphql/Mutations.ContactUs.cs, src/Hng.Graphql/Mutations.Subscriptions.cs, src/Hng.Graphql/Queries.ContactUs.cs, src/Hng.Graphql/Queries.Subscriptions.cs
=> Feat: Implement Subscription Management in Graphql

src/Hng.Application.Test/Features/UserManagement/LoginUserCommandShould.cs
This pr attempts to make a fix to the login command handler success test case
- Mock UserRepository IQuerable
- Partially Mock UserRepository IQuerable
=> partialfix(Tests): fix login test
